
SCRATCH=/lustre/atlas/scratch/dmeiser/fus048
cmake \
  -DHPCG_SOURCE_DIR=${SCRATCH}/HPCG/src/ \
  -DSUPRA_SEARCH_PATH=${SCRATCH}/software \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_CXX_COMPILER=CC \
  -DCMAKE_C_COMPILER=cc \
  -DMPI_CXX_COMPILER=CC \
  -DMPI_C_COMPILER=cc \
  -DENABLE_PARALLEL:BOOL=TRUE \
  -DENABLE_GPU_AWARE_MPI:BOOL=TRUE \
  -DCMAKE_INSTALL_PREFIX=${SCRATCH}/software/TxHPCG \
  ../libTxHPCG 
